

CREATE TABLE transaction (
    id integer generated by default as identity,
    amount float(53),
    recipient_id integer,
    sender_id integer,
    status varchar(255),
    timestamp timestamp(6),
    primary key (id)
);

CREATE TABLE user_account (
    id integer generated by default as identity,
    balance float(53),
    external_id varchar(255),
    name VARCHAR(255),
    PRIMARY KEY (id)
);

INSERT INTO user_account (id, external_id, name, balance) VALUES (1, 'alex-123', 'Alexander', 1000.00);
INSERT INTO user_account (id, external_id, name, balance) VALUES (2, 'maria-456', 'Maria', 500.00);
INSERT INTO user_account (id, external_id, name, balance) VALUES (3, 'john-789', 'John', 750.00);


INSERT INTO transaction (id, sender_id, recipient_id, amount, timestamp, status)
VALUES (1, 1, 2, 200.00, CURRENT_TIMESTAMP, 'SUCCESS');

INSERT INTO transaction (id, sender_id, recipient_id, amount, timestamp, status)
VALUES (2, 2, 3, 100.00, CURRENT_TIMESTAMP, 'SUCCESS');